### ISSUE TITLE
Delete some settings from the config creator.

### ISSUE THREAD

**Issue by DogancanYr** [otavepto/gbe_fork#46]
What is the point of achievements when there are disable_overlay_achievement_notification and disable_overlay settings ?

**Comment by BTFighter** [comment]
Both disable_overlay_achievement_notification and disable_overlay are optional.

I use disable_overlay_achievement_notification because I already have an application (Achievement Watcher) that pops up a better achievement notification than the built-in one.

I use disable_overlay because some games don't work with Goldberg's overlay, or crash when doing so. Also, experimental_steamclient always has the overlay on by default so having this option to games that are incompatible with Goldberg's overlay is very much needed.

Just because these options exist doesn't mean achievements are useless, they aren't even on by default. It will be up to the user to decide if they use these or not, as long as it's there when it's needed at some point.

**Comment by DogancanYr** [comment]
> EDIT: My mistake, didn't read the "config creator" part. You can just delete them if you don't want to use them. Also, maybe related to #45

Wouldn't it be better if it wasn't created by default?
